### ISSUE TITLE
Stuck on "Waiting for NANO node to fully initialize..." during setup.sh ?

### ISSUE THREAD

**Issue by OmarB97** [lephleg/nano-node-docker#13]
I'm running setup.sh with LetsEnrypt and I seem to be stuck:

```
root@node:~/nano-node-docker# sudo ./setup.sh $(cat settings)
 -----------------------
 NANO Node Docker v4.3
 -----------------------

=> Checking initial status...

=> Pulling images and spinning up containers...

nano-node-monitor is up-to-date
nginx-proxy is up-to-date
nginx-proxy-letsencrypt is up-to-date
watchtower is up-to-date
Recreating nano-node ... done

=> Waiting for NANO node to fully initialize...
```

Not sure what's going wrong here...

**Comment by earthlingdavey** [comment]
I can't be loads of help because I've not used the setup for a while. You can try a few things. 

Logs should appear in `nano-node` directory, as if you're not using docker.
Try running `top` command to see if you have a high cpu or memory usage.
Check disk space with `df –h`.

Checking them should give you an indication of if your node is syncing, or an error has occurred.
Good luck :)

**Comment by ryan-senn** [comment]
Running into the same issue, nano-node keeps restarting.
Here is what `docker ps` gives me
```
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                           PORTS                NAMES
9a4aad305d48        nanocurrency/nano:latest    "/bin/bash /usr/bin/…"   21 minutes ago      Restarting (135) 3 seconds ago                        nano-node
f7c8a04f4a44        nanotools/nanonodemonitor   "docker-php-entrypoi…"   16 hours ago        Up 16 hours                      0.0.0.0:80->80/tcp   nano-node-monitor
017dc9f2244c        v2tec/watchtower            "/watchtower watchto…"   16 hours ago        Up 16 hours                                           watchtower
```
`top` shows that nothing is really running (`top` uses the most resources).
`df –h /` shows that I still have space available.
I tried to stop and restart nano-node through docker a few times but no luck so far.

Edit:
I'm trying on a machine with better specs and it seems to be working (4GB ram, 2 CPU cores), although it's been stuck in the `Waiting for NANO node to fully initialize...` for a while. When I use `top` I can see `nano_node` running thought so I know it's doing something this time.

**Comment by EvoSteven** [comment]
The problem seems to be that ipv6 is not enabled by default in docker.

2 options:
1. Change RPC binding to ipv4, you can see the required changes here: https://github.com/EvoSteven/nano-node-docker/commit/0ae09b081bb8efa875ef06461a39700b2accc3f0
2. Enable ipv6 in docker: https://docs.docker.com/config/daemon/ipv6/

I've not personally tried option 2 here because 1 has fulfilled my needs and has allowed me to set my node up and a handful of others on the Nano Discord as well.

**Comment by lephleg** [comment]
This is indeed an issue related with your system ipv6 configuration. 

For local deployments with no ipv6 support consider changing the `"::1:7076:7076"` part of the `nano-node` service in `docker-compose.yml` and `docker-compose.letsencrypt.yml` to `"127.0.0.1:7076:7076"`.
